/**
 * Mock data for frontend development without backend
 */

export const mockAuthData = {
  access_token: 'mock-token-xyz',
  user: {
    id: 'user-1',
    email: 'recruiter@company.com',
    name: 'John Recruiter',
    role: 'hr',
  },
};

export const mockKpis = {
  total_candidates: 12,
  yet_to_interview: 7,
  interview_completed: 5,
  pending_re_interviews: 1,
};

export const mockCandidatesDetail = {
  'cand-001': {
    id: 'cand-001',
    candidate_id: 'cand-001',
    name: 'Alice Johnson',
    email: 'alice.johnson@email.com',
    phone: '9876543210',
    status: 'yet_to_interview',
    role: 'Backend Developer',
    role_applied: 'Backend Developer',
    applied_date: '2025-01-10',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 3,
    location: 'Mumbai',
    education: 'B.Tech CS',
    college: 'IIT Bombay',
    notes: 'Strong backend skills, good problem solving abilities',
    skills: ['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS'],
    linkedin: 'linkedin.com/in/alice-johnson',
    created_at: '2025-01-10T08:00:00Z',
    qualifications: 'B.Tech Computer Science',
  },
  'cand-002': {
    id: 'cand-002',
    candidate_id: 'cand-002',
    name: 'Bob Smith',
    email: 'bob.smith@email.com',
    phone: '9876543211',
    status: 'yet_to_interview',
    role: 'Frontend Developer',
    role_applied: 'Frontend Developer',
    applied_date: '2025-01-12',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 2,
    location: 'Bangalore',
    education: 'B.Tech IT',
    college: 'BITS Pilani',
    notes: 'Good React knowledge, responsive design expert',
    skills: ['React', 'JavaScript', 'CSS', 'HTML5', 'Figma'],
    linkedin: 'linkedin.com/in/bob-smith',
    created_at: '2025-01-12T08:00:00Z',
    qualifications: 'B.Tech Information Technology',
  },
  'cand-003': {
    id: 'cand-003',
    candidate_id: 'cand-003',
    name: 'Carol Davis',
    email: 'carol.davis@email.com',
    phone: '9876543212',
    status: 'interview_completed',
    role: 'Full Stack Developer',
    role_applied: 'Full Stack Developer',
    applied_date: '2025-01-08',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 5,
    location: 'Pune',
    education: 'B.Sc Computer Science',
    college: 'Pune University',
    notes: 'Excellent technical skills and communication',
    skills: ['Node.js', 'React', 'MongoDB', 'TypeScript', 'Git'],
    interview_status: 'selected',
    interview_date: '2025-01-15',
    interview_notes: 'Very impressive candidate, strong in both frontend and backend',
    linkedin: 'linkedin.com/in/carol-davis',
    created_at: '2025-01-08T08:00:00Z',
    qualifications: 'B.Sc Computer Science',
  },
  'cand-004': {
    id: 'cand-004',
    candidate_id: 'cand-004',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    phone: '9876543213',
    status: 'interview_completed',
    role: 'Backend Developer',
    role_applied: 'Backend Developer',
    applied_date: '2025-01-05',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 4,
    location: 'Delhi',
    education: 'B.Tech CSE',
    college: 'Delhi University',
    notes: 'Good knowledge but lacking in problem solving',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Microservices'],
    interview_status: 'rejected',
    interview_date: '2025-01-14',
    interview_notes: 'Good technical foundation but struggled with system design questions',
    linkedin: 'linkedin.com/in/david-wilson',
    created_at: '2025-01-05T08:00:00Z',
    qualifications: 'B.Tech Computer Science and Engineering',
  },
  'cand-005': {
    id: 'cand-005',
    candidate_id: 'cand-005',
    name: 'Emma Brown',
    email: 'emma.brown@email.com',
    phone: '9876543214',
    status: 'yet_to_interview',
    role: 'DevOps Engineer',
    role_applied: 'DevOps Engineer',
    applied_date: '2025-01-11',
    eligibility: 'ineligible',
    resume_url: '#',
    experience_years: 1,
    location: 'Hyderabad',
    education: 'B.Tech ECE',
    college: 'JNTU Hyderabad',
    notes: 'Limited experience, does not meet minimum requirements',
    skills: ['Docker', 'Kubernetes', 'AWS'],
    linkedin: 'linkedin.com/in/emma-brown',
    created_at: '2025-01-11T08:00:00Z',
    qualifications: 'B.Tech Electronics and Communication Engineering',
  },
  'cand-006': {
    id: 'cand-006',
    candidate_id: 'cand-006',
    name: 'Frank Miller',
    email: 'frank.miller@email.com',
    phone: '9876543215',
    status: 're_interview_pending',
    role: 'DevOps Engineer',
    role_applied: 'DevOps Engineer',
    applied_date: '2025-01-06',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 3,
    location: 'Chennai',
    education: 'B.Tech IT',
    college: 'Anna University',
    notes: 'Good DevOps experience, needs clarification on Kubernetes',
    skills: ['Kubernetes', 'Docker', 'Jenkins', 'Terraform', 'AWS', 'Azure'],
    re_interview_reason: 'Pending clarification on Kubernetes experience',
    linkedin: 'linkedin.com/in/frank-miller',
    created_at: '2025-01-06T08:00:00Z',
    qualifications: 'B.Tech Information Technology',
  },
  'cand-007': {
    id: 'cand-007',
    candidate_id: 'cand-007',
    name: 'Grace Lee',
    email: 'grace.lee@email.com',
    phone: '9876543216',
    status: 'yet_to_interview',
    role: 'QA Engineer',
    role_applied: 'QA Engineer',
    applied_date: '2025-01-13',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 2,
    location: 'Noida',
    education: 'B.Tech CSE',
    college: 'Delhi Technological University',
    notes: 'Strong test automation skills',
    skills: ['Selenium', 'TestNG', 'Java', 'API Testing', 'Cypress'],
    linkedin: 'linkedin.com/in/grace-lee',
    created_at: '2025-01-13T08:00:00Z',
    qualifications: 'B.Tech Computer Science and Engineering',
  },
  'cand-008': {
    id: 'cand-008',
    candidate_id: 'cand-008',
    name: 'Henry Chen',
    email: 'henry.chen@email.com',
    phone: '9876543217',
    status: 'interview_completed',
    role: 'Backend Developer',
    role_applied: 'Backend Developer',
    applied_date: '2025-01-04',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 6,
    location: 'Bangalore',
    education: 'M.Tech Computer Science',
    college: 'IISc Bangalore',
    notes: 'Exceptional technical knowledge and leadership potential',
    skills: ['Python', 'Go', 'Rust', 'Distributed Systems', 'AWS', 'GCP'],
    interview_status: 'selected',
    interview_date: '2025-01-13',
    interview_notes: 'Outstanding candidate with strong system design knowledge',
    linkedin: 'linkedin.com/in/henry-chen',
    created_at: '2025-01-04T08:00:00Z',
    qualifications: 'M.Tech Computer Science',
  },
  'cand-009': {
    id: 'cand-009',
    candidate_id: 'cand-009',
    name: 'Iris Patel',
    email: 'iris.patel@email.com',
    phone: '9876543218',
    status: 'yet_to_interview',
    role: 'Frontend Developer',
    role_applied: 'Frontend Developer',
    applied_date: '2025-01-09',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 2,
    location: 'Ahmedabad',
    education: 'B.Tech IT',
    college: 'Gujarat Technological University',
    notes: 'Creative UI/UX developer with design thinking',
    skills: ['React', 'Vue.js', 'CSS', 'Tailwind', 'Figma', 'Adobe XD'],
    linkedin: 'linkedin.com/in/iris-patel',
    created_at: '2025-01-09T08:00:00Z',
    qualifications: 'B.Tech Information Technology',
  },
  'cand-010': {
    id: 'cand-010',
    candidate_id: 'cand-010',
    name: 'Jack Thompson',
    email: 'jack.thompson@email.com',
    phone: '9876543219',
    status: 'interview_completed',
    role: 'Full Stack Developer',
    role_applied: 'Full Stack Developer',
    applied_date: '2025-01-07',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 4,
    location: 'Kolkata',
    education: 'B.Tech CSE',
    college: 'Calcutta University',
    notes: 'Well-rounded developer with good communication',
    skills: ['MERN Stack', 'Node.js', 'MongoDB', 'PostgreSQL', 'Docker'],
    interview_status: 'selected',
    interview_date: '2025-01-16',
    interview_notes: 'Good technical knowledge with practical project experience',
    linkedin: 'linkedin.com/in/jack-thompson',
    created_at: '2025-01-07T08:00:00Z',
    qualifications: 'B.Tech Computer Science and Engineering',
  },
  'cand-011': {
    id: 'cand-011',
    candidate_id: 'cand-011',
    name: 'Karen White',
    email: 'karen.white@email.com',
    phone: '9876543220',
    status: 'yet_to_interview',
    role: 'QA Engineer',
    role_applied: 'QA Engineer',
    applied_date: '2025-01-14',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 3,
    location: 'Jaipur',
    education: 'B.Tech CSE',
    college: 'Rajasthan Technical University',
    notes: 'Manual and automation testing expertise',
    skills: ['Selenium', 'Python', 'Manual Testing', 'Test Planning', 'JIRA'],
    linkedin: 'linkedin.com/in/karen-white',
    created_at: '2025-01-14T08:00:00Z',
    qualifications: 'B.Tech Computer Science and Engineering',
  },
  'cand-012': {
    id: 'cand-012',
    candidate_id: 'cand-012',
    name: 'Liam Martin',
    email: 'liam.martin@email.com',
    phone: '9876543221',
    status: 'interview_completed',
    role: 'Backend Developer',
    role_applied: 'Backend Developer',
    applied_date: '2025-01-03',
    eligibility: 'eligible',
    resume_url: '#',
    experience_years: 7,
    location: 'Mumbai',
    education: 'B.E. Computer Engineering',
    college: 'University of Mumbai',
    notes: 'Senior developer with team lead experience',
    skills: ['Java', 'Scala', 'Apache Kafka', 'Microservices', 'AWS'],
    interview_status: 'rejected',
    interview_date: '2025-01-12',
    interview_notes: 'Overqualified for role, expected higher compensation',
    linkedin: 'linkedin.com/in/liam-martin',
    created_at: '2025-01-03T08:00:00Z',
    qualifications: 'B.E. Computer Engineering',
  },
};

export const mockCandidates = Object.values(mockCandidatesDetail);

export const mockCandidateDetail = mockCandidatesDetail['cand-001'];

export const mockInterviewsYetToInterview = [
  mockCandidatesDetail['cand-001'],
  mockCandidatesDetail['cand-002'],
  mockCandidatesDetail['cand-005'],
  mockCandidatesDetail['cand-007'],
  mockCandidatesDetail['cand-009'],
  mockCandidatesDetail['cand-011'],
].filter(c => c.status === 'yet_to_interview');

export const mockInterviewsCompleted = [
  mockCandidatesDetail['cand-003'],
  mockCandidatesDetail['cand-004'],
  mockCandidatesDetail['cand-008'],
  mockCandidatesDetail['cand-010'],
  mockCandidatesDetail['cand-012'],
].filter(c => c.status === 'interview_completed');

export const mockReInterviewRequests = [
  {
    id: 're-001',
    candidate_id: 'cand-006',
    candidate_name: 'Frank Miller',
    email: 'frank.miller@email.com',
    role: 'DevOps Engineer',
    reason: 'Pending clarification on Kubernetes experience',
    status: 'pending',
    request_date: '2025-01-20',
  },
];

export const mockReports = {
  by_status: {
    yet_to_interview: 5,
    interview_completed: 6,
    pending_re_interview: 1,
  },
  by_role: {
    'Backend Developer': 4,
    'Frontend Developer': 2,
    'Full Stack Developer': 2,
    'DevOps Engineer': 2,
    'QA Engineer': 2,
  },
  by_decision: {
    selected: 4,
    rejected: 2,
  },
  by_eligibility: {
    eligible: 11,
    ineligible: 1,
  },
};

export const mockAuditLogs = [
  {
    id: 'log-001',
    timestamp: '2025-01-22T10:30:00Z',
    user: 'John Recruiter',
    action: 'interview_submitted',
    details: 'Interview completed for Alice Johnson - Decision: Selected',
  },
  {
    id: 'log-002',
    timestamp: '2025-01-22T09:15:00Z',
    user: 'John Recruiter',
    action: 'candidate_viewed',
    details: 'Viewed candidate profile: Bob Smith (cand-002)',
  },
  {
    id: 'log-003',
    timestamp: '2025-01-21T16:45:00Z',
    user: 'John Recruiter',
    action: 'search_performed',
    details: 'Searched candidates with role: Backend Developer',
  },
  {
    id: 'log-004',
    timestamp: '2025-01-21T14:20:00Z',
    user: 'John Recruiter',
    action: 'candidate_viewed',
    details: 'Viewed candidate profile: Carol Davis (cand-003)',
  },
  {
    id: 'log-005',
    timestamp: '2025-01-21T11:00:00Z',
    user: 'John Recruiter',
    action: 'interview_submitted',
    details: 'Interview completed for David Wilson - Decision: Rejected',
  },
];

export const mockSyncStatus = {
  last_sync: '2025-01-22T10:00:00Z',
  status: 'success',
  total_synced: 12,
  message: 'All data synced successfully',
};
